Update function _optimize_upstream based on monitor metric

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -172,6 +172,54 @@ _optimize_upstream_file() {
 	fi
 	rm $_node_ids
 }
+_optimize_upstream_geo() {
+	node_scores=$1
+	_upstream_country=$(mktemp)
+	_upstream_continent=$(mktemp)
+	_upstream_other=$(mktemp)
+	awk '$2 > 100000{printf "server unix:/tmp/%s.sock max_fails=1 fail_timeout=3s weight=%s;\n",$1, $2}' $_node_scores >$_upstream_country
+	awk '$2 <= 100000 && $2 > 10000{printf "server unix:/tmp/%s.sock max_fails=1 fail_timeout=3s weight=%s;\n",$1, $2}' $_node_scores >$_upstream_continent
+	awk '$2 <= 10000{printf "server unix:/tmp/%s.sock max_fails=1 fail_timeout=3s weight=%s;\n",$1, $2}' $_node_scores >$_upstream_other
+
+	_upstream_country_n=$(wc -l $_upstream_country | cut -d' ' -f1)
+	_upstream_continent_n=$(wc -l $_upstream_continent | cut -d' ' -f1)
+	_upstream_other_n=$(wc -l $_upstream_other | cut -d' ' -f1)
+
+	if [ $_upstream_country_n -ge 1 ]; then
+		_fn=http.d/${blockchain}-${network}-${continent}-${country}.upstream
+		if [ -f "$_fn" ]; then
+			cp $_fn ${_fn}.bk1
+			cp $_upstream_country $_fn
+		fi
+	fi
+
+	if [ $_upstream_continent_n -ge 1 ]; then
+		_fn=http.d/${blockchain}-${network}-${continent}-${country}-v1-v2.upstream
+		if [ -f "$_fn" ]; then
+			cp $_fn ${_fn}.bk1
+			cp $_upstream_continent $_fn
+		fi
+	fi
+	if [ $_upstream_other_n -ge 1 ]; then
+		_fn=http.d/${blockchain}-${network}-${continent}-${country}-v1.upstream
+		if [ -f "$_fn" ]; then
+			cp $_fn ${_fn}.bk1
+			cp $_upstream_other $_fn
+		fi
+	fi
+
+	echo "Upstream country"
+	cat $_upstream_country
+
+	echo "Upstream continent"
+	cat $_upstream_continent
+
+	echo "Upstream other"
+	cat $_upstream_other
+
+	rm $_upstream_continent $_upstream_country $_upstream_other
+
+}
 _optimize_upstream() {
 	blockchain=$1
 	network=$2
@@ -182,11 +230,16 @@ _optimize_upstream() {
 	node_monitor=/tmp/node_monitor
 	node_scores=/tmp/node_scores
 	timeout 3 curl -sSfL https://${TYPE}-${blockchain}-${network}.monitor.mbr.${DOMAIN}/_stat/$TYPE/$blockchain/$network/$id/mbr-node | sort -k1 >$node_monitor
+	if [ $? -ne 0 ]; then return; fi
+	_tmp="$(cat $node_monitor)"
+	if [ -z "$_tmp" ]; then return; fi
 	_optimize_upstream_file http.d/${blockchain}-${network}.upstream $node_monitor $node_scores
 	_optimize_upstream_file http.d/${blockchain}-${network}-${continent}.upstream $node_monitor
 	_optimize_upstream_file http.d/${blockchain}-${network}-${continent}-${country}.upstream $node_monitor
 	_optimize_upstream_file http.d/${blockchain}-${network}-${continent}-${country}-v1.upstream $node_monitor
 	_optimize_upstream_file http.d/${blockchain}-${network}-${continent}-${country}-v1-v2.upstream $node_monitor
+
+	_optimize_upstream_geo $node_scores
 }
 _update_network() {
 	PORTAL_URL=$(cat $SITE_ROOT/vars/PORTAL_URL)
