fix: read domain,mbr_env,portal_url from vars

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -20,23 +20,44 @@ debug_log=$SITE_ROOT/logs/debug.log
 export GIT_PUBLIC_URL="https://github.com"
 
 _save_env() {
+	if [ -z "$SESSION_ENABLE" ]; then
+		export SESSION_ENABLE=""
+	fi
+
+	if [ -n "$MBR_ENV" ]; then
+		echo $MBR_ENV >$SITE_ROOT/vars/MBR_ENV
+	fi
+
 	if [ -z "$MBR_ENV" ]; then
-		echo "MBR_ENV missing"
-		exit 1
+		if [ -f "$SITE_ROOT/vars/MBR_ENV" ]; then
+			export MBR_ENV=$(cat $SITE_ROOT/vars/MBR_ENV)
+		else
+			echo "MBR_ENV missing"
+			exit 1
+		fi
+	fi
+
+	if [ -n "$PORTAL_URL" ]; then
+		echo $PORTAL_URL >$SITE_ROOT/vars/PORTAL_URL
 	fi
 
 	if [ -z "$PORTAL_URL" ]; then
-		echo "PORTAL_URL missing"
-		exit 1
-	else
-		echo $PORTAL_URL >$SITE_ROOT/vars/PORTAL_URL
-	fi
-	if [ -z "$DOMAIN" ]; then
-		DOMAIN=$(echo $PORTAL_URL | cut -d'.' -f2-)
+		if [ -f "$SITE_ROOT/vars/PORTAL_URL" ]; then
+			export PORTAL_URL=$(cat $SITE_ROOT/vars/PORTAL_URL)
+		else
+			echo "PORTAL_URL missing"
+			exit 1
+		fi
 	fi
 
-	if [ -z "$SESSION_ENABLE" ]; then
-		export SESSION_ENABLE=""
+	if [ -z "$DOMAIN" ]; then
+		if [ -f "$SITE_ROOT/vars/DOMAIN" ]; then
+			export DOMAIN=$(cat $SITE_ROOT/vars/DOMAIN)
+		fi
+	fi
+
+	if [ -z "$DOMAIN" ]; then
+		DOMAIN=$(echo $PORTAL_URL | cut -d'.' -f2-)
 	fi
 
 	if [ -z "$DOMAIN" ]; then
@@ -54,8 +75,12 @@ EOF
 }
 _repo() {
 	if [ -z "$MBR_ENV" ]; then
-		echo "MBR_ENV missing"
-		exit 1
+		if [ -f "$SITE_ROOT/vars/MBR_ENV" ]; then
+			export MBR_ENV=$(cat $SITE_ROOT/vars/MBR_ENV)
+		else
+			echo "MBR_ENV missing"
+			exit 1
+		fi
 	fi
 	REPOS=""
 }
